### ISSUE TITLE
max-width and max-height are not supported by Kindle readers

### ISSUE THREAD

**Issue by CrazyCoder** [rupor-github/fb2mobi#22]
`default.css` contains the following:

```
.image img {
    max-width:100%; 
    max-height:100%;
}
```

When converting a book, kindlegen reports the following:

```
Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'max-width' in file: C:\Users\serge\AppData\Local\Temp\tmpizlduo59\OEBPS\stylesheet.css


Warning(htmlprocessor):W28001: CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'max-height' in file: C:\Users\serge\AppData\Local\Temp\tmpizlduo59\OEBPS\stylesheet.css
```

Probably this section can be removed from CSS.

**Comment by rupor-github** [comment]
default.css in distribution is an example only - it is supposed to be customized by users.

Having said that - fb2mobi sometimes is used to produce epub files where those properties actually make sense. Since there is no harm in having those warnings (and the alternative is to offer different sample default.css files) I do not see this going away any time soon.
